re-add ws_share changes with improvements from comments

diff --git a/bin/ws_share b/bin/ws_share
--- a/bin/ws_share
+++ b/bin/ws_share
@@ -1,7 +1,8 @@
 #!/bin/bash
 #
-# ws_share is a helper script that can be used to grant quickly read access for
-# a workspace to other users based on UNIX ACLs.
+# ws_share is a helper script that can be used to grant quickly read or
+# read-write access for a workspace to other users or groups based on UNIX ACLs.
+
 # See ws_share --help to get usage information.
 #
 # Known issues:
@@ -17,38 +18,49 @@
 #
 
 progname=$(basename $0)
+maxmembers=100 # do not share with a group with more than $maxmembers members
 
 # Test for compatible getopt version.
 # The parser needs an enhanced version of getopt.
 # See man page of getopt for this test.
 getopt --test
 if [[ $? -ne 4 ]]; then
-    echo "Error: $progname needs an enhaced getopt to work."
+    echo "Error: $progname needs an enhanced getopt to work."
     exit 1
 fi
 
 function print_version() {
-    echo "workspace version 1.5.0"
+    # also could call ws_allocate without finding path as running unprivileged
+    # but this way more likely we show the correct version
+    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+    "$SCRIPT_DIR"/ws_allocate --version
 }
 
 function usage() {
 cat <<EOF
-$progname allows to share an existing workspace with other users.
+$progname allows to share an existing workspace with other users or groups.
 
 usage:
 
 The following commands share / unshare a workspace (WS_NAME) with users:
- $progname share [-F FILESYSTEM] WS_NAME USER [USER...]
- $progname unshare [-F FILESYSTEM] WS_NAME USER [USER...]
+ $progname [--readwrite] share [-F FILESYSTEM] WS_NAME USER [USER...]
+ $progname [--readwrite] unshare [-F FILESYSTEM] WS_NAME USER [USER...]
+
+With groups:
+ $progname [--readwrite] sharegroup [-F FILESYSTEM] WS_NAME GROUP [GROUP...]
+ $progname [--readwrite] unsharegroup [-F FILESYSTEM] WS_NAME GROUP [GROUP...]
+
+Remove all ACLs from a workspace:
  $progname unshare-all [-F FILESYSTEM] WS_NAME
 
-Users that were granted read access to a workspace (WS_NAME) can be listed with
+List users/groups with ACL entries:
  $progname list WS_NAME
 
 options:
    -F, --filesystem  ws filesystem
    -h, --help        show this help
        --version     show version information and exit
+       --readwrite   grant read/write instead of read-only access
 
 EOF
 }
@@ -56,7 +68,7 @@ EOF
 
 # parse command line, based on example provided by util-linux
 OPTIONS=F:h
-LONG_OPTIONS=filesystem:,help,version
+LONG_OPTIONS=filesystem:,help,version,readwrite
 PARSED=$(getopt --options=$OPTIONS --longoptions=$LONG_OPTIONS --name "$0" -- "$@")
 if [[ $? -ne 0 ]]; then
     echo "Error: Command line error"
@@ -66,6 +78,7 @@ fi
 eval set -- "$PARSED"
 unset PARSED
 
+ACCESS="rX"  # default: read-only
 # parse options
 while true; do
     case "$1" in
@@ -80,6 +93,10 @@ while true; do
         --version)
             print_version
             exit 0
+            ;;
+        --readwrite)
+            ACCESS="rwX"
+            shift
             ;;
         --)
             shift
@@ -114,20 +131,19 @@ fi
 
 case $ACTION in
     list)
-        getfacl -ap --omit-header "$WS_PATH" | grep user | cut -d : -f 2 | grep -v '^$'
+        getfacl -apt "$WS_PATH" | awk '/user|group|USER|GROUP/&&!/---/{gsub("rw.","readwrite");gsub("r-.","read");print}'
         ;;
     share)
         USERS="$@"
         MACL=""
         for user in $USERS; do
-            id "$user" >/dev/null 2>&1
-            if [[ $? -ne 0 ]]; then
+            if ! id "$user" >/dev/null 2>&1; then
                 echo "Error: User $user unknown"
                 exit 1
             fi
-            echo "Granting access for $user ..."
-            MACL+="user:$user:rX,"
-            MACL+="default:user:$user:rX,"
+            echo "Granting $ACCESS access for user $user ..."
+            MACL+="user:$user:$ACCESS,"
+            MACL+="default:user:$user:$ACCESS,"
         done
         if [[ -z "$MACL" ]]; then
             # nothing to do
@@ -139,8 +155,7 @@ case $ACTION in
         USERS="$@"
         XACL=""
         for user in $USERS; do
-            id "$user" >/dev/null 2>&1
-            if [[ $? -ne 0 ]]; then
+            if ! id "$user" >/dev/null 2>&1; then
                 echo "Error: User $user unknown"
                 exit 1
             fi
@@ -149,12 +164,59 @@ case $ACTION in
             XACL+="default:user:$user,"
         done
         if [[ -z "$XACL" ]]; then
-            # nothing to do
             exit 0
         fi
         setfacl -R -x "$XACL" "$WS_PATH"
         ;;
+    sharegroup)
+        GROUPS="$@"
+        MACL=""
+        for group in $GROUPS; do
+            line=$(getent group "$group")
+            if [[ -z "$line" ]]; then
+                echo "Error: Group $group unknown"
+                exit 1
+            fi
+            if [[ $(echo "$line" | awk -F "," '{print NF-1}') -gt $maxmembers ]] ; then 
+                echo Too many members in group, please do not share worldwide ; 
+                exit 1; 
+            fi
+            echo "Granting $ACCESS access for group $group ..."
+            MACL+="group:$group:$ACCESS,"
+            MACL+="default:group:$group:$ACCESS,"
+        done
+        if [[ -n "$MACL" ]]; then
+          if [[ ACCESS == "rwX" ]] ; then
+              echo "Warning: giving write access to your group may:"
+              echo "  * immediate workspace deletion"
+              echo "  * interfere with your quota (depending on system setup)"
+              read -p "Continue (y/N)? " answer
+                 case "$answer" in
+                    [yY]*) ;;
+                    *) echo "Aborted."; exit 1 ;;
+                 esac
+          setfacl -R -m "$MACL" "$WS_PATH"
+        fi
+        ;;
+    unsharegroup)
+        GROUPS="$@"
+        XACL=""
+        for group in $GROUPS; do
+            if ! getent group "$group" >/dev/null; then
+                echo "Error: Group $group unknown"
+                exit 1
+            fi
+            echo "Removing access for group $group"
+            echo "Warning: will produce errors on files not owned by you"
+            sleep 3;
+            XACL+="group:$group,"
+            XACL+="default:group:$group,"
+        done
+        [[ -n "$XACL" ]] && setfacl -R -x "$XACL" "$WS_PATH"
+        ;;
     unshare-all)
+        echo "Warning: will produce errors on files not owned by you"
+        sleep 3;
         setfacl -R -b "$WS_PATH"
         ;;
     check)
